{
	"version": 1486157206,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/arrowdispenser-sheet0.png",
		"images/arrows-sheet0.png",
		"images/cathead-sheet0.png",
		"images/cathead-sheet1.png",
		"images/cheese-sheet0.png",
		"images/fireball-sheet0.png",
		"images/fireball-sheet1.png",
		"images/quicklitter-sheet0.png",
		"images/spring-sheet0.png",
		"images/spring-sheet1.png",
		"images/spring-sheet2.png",
		"images/scythe-sheet0.png",
		"images/spear-sheet0.png",
		"images/spearcontraption-sheet0.png",
		"images/spikes-sheet0.png",
		"images/lv01_map.png",
		"images/imeow_hud-sheet0.png",
		"images/imeow_portrait-sheet0.png",
		"images/imeow_portrait-sheet1.png",
		"images/imeow_trigger-sheet0.png",
		"images/bounds-sheet0.png",
		"images/indiana-sheet0.png",
		"images/exit-sheet0.png",
		"images/initialrespawnpoint-sheet0.png",
		"images/jumppoint-sheet0.png",
		"images/respawnpoint-sheet0.png",
		"images/camera-sheet0.png",
		"images/trap_trigger-sheet0.png",
		"images/handtutorial-sheet0.png",
		"images/handtutorial-sheet1.png",
		"images/pause-sheet0.png",
		"images/restart_btn-sheet0.png",
		"images/tilemap.png",
		"images/start_btn-sheet0.png",
		"images/credits_btn-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite3-sheet0.png",
		"images/eye-sheet0.png",
		"images/sprite-sheet0.png",
		"images/hudmenu-sheet0.png",
		"images/exithud-sheet0.png",
		"images/menu_btn-sheet0.png",
		"images/imeowtaphand-sheet0.png",
		"images/handrespawnpoint-sheet0.png",
		"images/tbstartscreen.png",
		"images/button-sheet0.png",
		"images/blackbg.png",
		"images/logo-sheet0.png",
		"images/star_score-sheet0.png",
		"images/star_score-sheet1.png",
		"images/continue_btn-sheet0.png",
		"media/bola de fogo.m4a",
		"media/bola de fogo.ogg",
		"media/mola.m4a",
		"media/mola.ogg",
		"media/flecha_new.m4a",
		"media/flecha_new.ogg",
		"media/foice_new.m4a",
		"media/foice_new.ogg",
		"media/areia_movediça_new.m4a",
		"media/areia_movediça_new.ogg",
		"media/cartoon battle.m4a",
		"media/cartoon battle.ogg",
		"media/mountain emperor.m4a",
		"media/mountain emperor.ogg",
		"media/bensound-funkyelement.m4a",
		"media/bensound-funkyelement.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"lithos_pro_black-webfont.woff",
		"lithos_pro_regular-webfont.woff",
		"stylesheet.css"
	]
}